language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t msjaison135/docker-react -f Dockerfile.dev .

script:
  - docker run msjaison135/docker-react npm run test -- --coverage



